export const EncryptionMethodsDetails = {
  atbash: {
    year: '600 B.C.',
    crack: true,
    timeline: true,
    timelineIdx: 0,
    display: 'Atbash',
    name: 'atbash',
  },
  skytale: {
    year: '300 B.C.',
    crack: false,
    timeline: true,
    timelineIdx: 1,
    display: 'Skytale',
    name: 'skytale',
  },
  caesar: {
    year: '100 B.C. - 44 B.C.',
    crack: true,
    timeline: true,
    timelineIdx: 2,
    display: "Caesar's",
    name: 'caesar',
  },
  vigenere: {
    year: '1553',
    crack: false,
    timeline: true,
    timelineIdx: 3,
    display: 'Vigenère',
    name: 'vigenere',
  },
  morse: {
    year: '1837',
    crack: false,
    timeline: true,
    timelineIdx: 4,
    display: 'Morse Code',
    name: 'morse',
  },
  playfair: {
    year: '1854',
    crack: false,
    timeline: true,
    timelineIdx: 5,
    display: 'Playfair',
    name: 'playfair',
  },
  nihilist: {
    year: '1880',
    crack: false,
    timeline: true,
    timelineIdx: 6,
    display: 'Nihilist',
    name: 'nihilist',
  },
  otp: {
    year: '1882',
    crack: false,
    timeline: true,
    timelineIdx: 7,
    display: 'OTP',
    name: 'otp',
  },
  trifid: {
    year: '1902',
    crack: false,
    timeline: true,
    timelineIdx: 8,
    display: 'Trifid',
    name: 'trifid',
  },
  rsa: {
    year: '1977',
    crack: false,
    timeline: true,
    timelineIdx: 9,
    display: 'RSA',
    name: 'rsa',
  },
  affine: {
    year: false,
    crack: false,
    timeline: false,
    timelineIdx: -1,
    display: 'Affine',
    name: 'affine',
  },
  rot13: {
    year: false,
    crack: false,
    timeline: false,
    timelineIdx: -1,
    display: 'Rot 13',
    name: 'rot13',
  },
  replace: {
    year: false,
    crack: false,
    timeline: false,
    timelineIdx: -1,
    display: 'Replace',
    name: 'replace',
  },
  reverse: {
    year: false,
    crack: false,
    timeline: false,
    timelineIdx: -1,
    display: 'Reverse',
    name: 'reverse',
  },
  casetransform: {
    year: false,
    crack: false,
    timeline: false,
    timelineIdx: -1,
    display: 'Case',
    name: 'casetransform',
  },
  substitution: {
    year: false,
    crack: false,
    timeline: false,
    timelineIdx: -1,
    display: 'Substitution',
    name: 'substitution',
  },
};
