export const EncryptionMethodsDetails = {
  atbash: {
    year: '600 B.C.',
    crack: false,
    timeline: true,
    timelineIdx: 0,
    display: 'Atbash',
    name: 'atbash',
    fullName: 'Atbash Cipher',
    category: 'Ciphers',
  },
  skytale: {
    year: '300 B.C.',
    crack: false,
    timeline: true,
    timelineIdx: 1,
    display: 'Skytale',
    name: 'skytale',
    fullName: 'Skytale',
    category: 'Ciphers',
  },
  caesar: {
    year: '100 B.C. - 44 B.C.',
    crack: false,
    timeline: true,
    timelineIdx: 2,
    display: "Caesar's",
    name: 'caesar',
    fullName: 'Caesars Cipher',
    category: 'Ciphers',
  },
  vigenere: {
    year: '1553',
    crack: false,
    timeline: true,
    timelineIdx: 3,
    display: 'Vigenère',
    name: 'vigenere',
    fullName: 'Vigenère Cipher',
    category: 'Polyalphabetic Ciphers',
  },
  morse: {
    year: '1837',
    crack: false,
    timeline: true,
    timelineIdx: 4,
    display: 'Morse Code',
    name: 'morse',
    fullName: 'Morse Code',
    category: 'Alphabets',
  },
  playfair: {
    year: '1854',
    crack: false,
    timeline: true,
    timelineIdx: 5,
    display: 'Playfair',
    name: 'playfair',
    fullName: 'Playfair Cipher',
    category: 'Ciphers',
  },
  nihilist: {
    year: '1880',
    crack: false,
    timeline: true,
    timelineIdx: 6,
    display: 'Nihilist',
    name: 'nihilist',
    fullName: 'Nihilist Cipher',
    category: 'Polybius Square Ciphers',
  },
  otp: {
    year: '1882',
    crack: false,
    timeline: true,
    timelineIdx: 7,
    display: 'OTP',
    name: 'otp',
    fullName: 'One Time Pad',
    category: 'Ciphers',
  },
  trifid: {
    year: '1902',
    crack: false,
    timeline: true,
    timelineIdx: 8,
    display: 'Trifid',
    name: 'trifid',
    fullName: 'Trifid Cipher',
    category: 'Polybius Square Ciphers',
  },
  rsa: {
    year: '1977',
    crack: false,
    timeline: true,
    timelineIdx: 9,
    display: 'RSA',
    name: 'rsa',
    fullName: 'Rivest-Shamir-Adleman Cryptosystem',
    category: 'Public Key Encryption',
  },
  affine: {
    year: false,
    crack: false,
    timeline: false,
    timelineIdx: -1,
    display: 'Affine',
    name: 'affine',
    fullName: 'Affine Cipher',
    category: 'Ciphers',
  },
  rot13: {
    year: false,
    crack: false,
    timeline: false,
    timelineIdx: -1,
    display: 'Rot 13',
    name: 'rot13',
    fullName: 'Rot 13',
    category: 'Ciphers',
  },
  replace: {
    year: false,
    crack: false,
    timeline: false,
    timelineIdx: -1,
    display: 'Replace',
    name: 'replace',
    fullName: 'Replace',
    category: 'Text Transformations',
  },
  reverse: {
    year: false,
    crack: false,
    timeline: false,
    timelineIdx: -1,
    display: 'Reverse',
    name: 'reverse',
    fullName: 'Reverse',
    category: 'Text Transformations',
  },
  casetransform: {
    year: false,
    crack: false,
    timeline: false,
    timelineIdx: -1,
    display: 'Case',
    name: 'casetransform',
    fullName: 'Case Transforms',
    category: 'Text Transformations',
  },
  substitution: {
    year: false,
    crack: false,
    timeline: false,
    timelineIdx: -1,
    display: 'Substitution',
    name: 'substitution',
    fullName: 'Substitution Cipher',
    category: 'Ciphers',
  },
};
